# encoding: utf-8
# copyright: 2016, you
# license: All rights reserved
# date: 2015-05-26
# description: The Red Hat Enterprise Linux 6 Security Technical Implementation Guide (STIG) is published as a tool to improve the security of Department of Defense (DoD) information systems.  Comments or proposed revisions to this document should be sent via e-mail to the following address: disa.stig_spt@mail.mil.
# impacts

title 'V-38628 - The operating system must produce audit records containing sufficient information to establish the identity of any user/subject associated with the event.'

control 'V-38628' do
  impact 0.5
  title 'The operating system must produce audit records containing sufficient information to establish the identity of any user/subject associated with the event.'
  desc '
Ensuring the "auditd" service is active ensures audit records generated by the kernel can be written to disk, or that appropriate actions will be taken if other obstacles exist.
'
  tag 'stig','V-38628'
  tag severity: 'medium'
  tag checkid: 'C-46186r1_chk'
  tag fixid: 'F-43576r2_fix'
  tag version: 'RHEL-06-000145'
  tag ruleid: 'SV-50429r2_rule'
  tag fixtext: '
The "auditd" service is an essential userspace component of the Linux Auditing System, as it is responsible for writing audit records to disk. The "auditd" service can be enabled with the following commands: 

# chkconfig auditd on
# service auditd start
'
  tag checktext: '
Run the following command to determine the current status of the "auditd" service: 

# service auditd status

If the service is enabled, it should return the following: 

auditd is running...


If the service is not running, this is a finding.
'

# START_CHECKS
  # describe file('/etc') do
  #  it { should be_directory }
  #end
# END_CHECKS
end
